import type { PlateLayerDef } from '../contracts/assets.ts';
import type { Extent } from '../render/util/camera.ts';

/**
 * Painted-plate layout (ARCHITECTURE.md §5.8), shared by the bake tools and the runtime.
 *
 * A chunk texture is PLATE_TEXTURE² texels: PLATE_CONTENT² texels of content plus a PLATE_BORDER-texel
 * ring duplicated from the neighbouring chunks (transparent at the image edge). The manifest's
 * `chunkSize` is the content size (the step between chunks); `core`/`soft` rects are in content texels,
 * and the runtime maps content texel x to texture u = (border + x) / textureWidth.
 *
 * Why 4 texels: bilinear filtering of mip 0 needs 1, but KTX2 mip 1 (drawn at Low and under dynamic
 * resolution, KIT_MAX_MIP = 1) is generated by basisu with a Kaiser filter that reads about 3 mip-0 texels
 * around each mip-1 texel and wraps around the texture edge. With 4 shared texels the mip-1 texels
 * sampled at a seam are computed from the same source texels on both sides, and a 1016-texel step (a
 * multiple of 8) keeps the 4×4 compression blocks of mips 0 and 1 aligned across the seam too.
 */
export const PLATE_TEXTURE = 1024;
export const PLATE_BORDER = 4;
export const PLATE_CONTENT = PLATE_TEXTURE - 2 * PLATE_BORDER;
/** World units per plate texel, at least: WebP/PNG chunks have no mipmaps (≤ 2× minification at Low). */
export const PLATE_MIN_TEXEL_SCALE = 1.5;
/** Largest source image side (texels). */
export const PLATE_MAX_SOURCE = 16384;
/** Layer-space prefetch margin of the plate streamer (the budget sweep warns with it included). */
export const PLATE_PREFETCH_MARGIN = 480;
/** A plate layer may never show more chunks than this at once (2 draws each: core + soft). */
export const PLATE_MAX_VISIBLE_CHUNKS = 4;
/** Chunk loads still pending after this long count as failed (KTX2 has its own, shorter deadline). */
export const PLATE_LOAD_TIMEOUT_MS = 20000;

type Placement = Pick<PlateLayerDef, 'origin' | 'chunkSize' | 'texelScale'>;

/** Layer-space rect of chunk (col, row)'s content. */
export function plateChunkRect(def: Placement, col: number, row: number, out: Extent = { x0: 0, y0: 0, x1: 0, y1: 0 }): Extent {
  const [cw, ch] = def.chunkSize;
  const ts = def.texelScale;
  out.x0 = def.origin[0] + col * cw * ts;
  out.y0 = def.origin[1] + row * ch * ts;
  out.x1 = out.x0 + cw * ts;
  out.y1 = out.y0 + ch * ts;
  return out;
}

/** Texture size of a chunk: content plus the duplicated border. */
export function plateTextureSize(def: Pick<PlateLayerDef, 'chunkSize'>): [number, number] {
  return [def.chunkSize[0] + 2 * PLATE_BORDER, def.chunkSize[1] + 2 * PLATE_BORDER];
}

/** GPU bytes of one chunk in the worst case the budgets assume: RGBA8, no mipmaps. */
export function plateChunkBytes(def: Pick<PlateLayerDef, 'chunkSize'>): number {
  const [w, h] = plateTextureSize(def);
  return 4 * w * h;
}

/**
 * Border of a loaded chunk texture: (texture size − content size) / 2 on both axes, or null when the
 * texture does not match the layer's chunk size (the chunk is then treated as failed). A border of 0
 * accepts unbordered textures from hand-edited manifests.
 */
export function plateTextureBorder(def: Pick<PlateLayerDef, 'chunkSize'>, width: number, height: number): number | null {
  const bx = (width - def.chunkSize[0]) / 2;
  const by = (height - def.chunkSize[1]) / 2;
  if (bx !== by || !Number.isInteger(bx) || bx < 0 || bx > PLATE_BORDER) return null;
  return bx;
}

/** Strip the query and fragment of a manifest path (texture URLs carry `?v=<hash8>`). */
export function pathnameOf(path: string): string {
  const q = path.search(/[?#]/);
  return q < 0 ? path : path.slice(0, q);
}

/** First 8 hex digits of a chunk hash: the `?v=` cache-buster of its texture URLs. */
export function hash8(hash: string): string {
  return hash.slice(0, 8);
}
